language: node_js
node_js:
- '6.1'

deploy:
  app: bikedeboa-api
  provider: heroku
  api_key:
    secure: lCGkhlmoHqJ9SxCJIKtaUUrC/GuiQu7sjx9s4gvbb4IBRRhWPhthSGjsGytUhlx8RiFK8zN3kli2/z/JAl6654hvgWUH+KjPQWsMpDJlZFTUv8xQJGw22X3vTxsEBhttI4xxfrZFtFtPA91FdWioss6cBxufpJPgwIFqUJrPNPXJ1e/bdsxq7RQNVFyQ+GdoZ8Wl/bgasGYFi0iozT2Ob3gUc7kzQHQi9dKanxVczydC7KCVmcKIkvwuzJ38OcdPaH+gDJRjjgfGf/IVOT+p/rXmmRFaiJUCcmkREPADdykI9DVrTowsC2d63GgS4Bv3LQwWZ/01UHMA/exc7GzL1hk8cjVra/7cx91b4KfDcezuY2G3nZsfA7EIt309dXtfmjIX3XBaeJIpMwTH89nEEAZrRBg+l+5Smcgnrv1jAD2SYGSisiq9SjcS4dL4OFwI6kpuF2QGlfGpUkUnzB7ekcitay2hnB7FyZgsK0RSePGhy+/8gWquXIWVx05G7rT4eEcpcSl1wc8zq9ruIrmvKCg7hJCNsFVHEZUKpGZeMueUD2mw/FwHeyngmL/XCryefuu0H3Z/ei6o6bCwZoD4GrL7nyFE/2kspUhMQO/nNVAHwWp7VGbycqUkOVKBgVUqV2x43bbJQs8IUglfLQMVi4A5gsN3gFiJPKB3lfiDndA=
